#!/bin/bash

usage()
{
echo "
Usage: git nostr [command] [--help]

Commands:
  help             get help about a command
  publish           upload commits to nostr as patches
  deleteall         send delete request for all messages for key pair
  list              list git repo manifest ids
  clone             git init, set nostr config, fetch patches for author and apply to local repo
  create            set git config.publickey to public key and upload all config patches to nostr
  pull              fetch patches for an author or manifestid and apply
  fork              clone a repo, then create
  forks             list forks of a repo
  issue             create an issue for a repo
  issues            list issues for a repo
  pullrequest, pr   create a pull request for a repo
  pullrequests, prs list pull requests for a repo

  log           (not implemented) List history of updates to a repo
  authors       (not implemented) List contributors to a repo
  name          (not implemented) Name a repo
  named         (not implemented) Search for repos by name
  web           (not implemented) Serve a web server for repos

  reconstruct   (not implemented) Reconstruct blobs for a git-update nostr message
  find-object   (not implemented) Find a git object in a repo
 "
exit 1
}

if [ $# -lt 1 ]
then
  usage
fi

case $1 in
  publish) # display Help
    shift
    # echo `publish.sh "$@" |tee >(head -n1) >(wc -l) >/dev/null`" nostr events created"
    publish.sh "$@"
    exit;;
  deleteall)
    shift
    deleteall.sh "$@"
    exit;;
  list)
    shift
    list.sh "$@"
    exit;;
  clone)
    shift
    clone.sh "$@"
    exit;;
  create) # run git init, set nostr.privatekey, set nostr.relay
    shift
    create.sh "$@"
    exit;;
  pull)
    shift
    pull.sh "$@"
    exit;;
  fork)
    shift
    fork.sh "$@"
    exit;;
  forks)
    shift
    forks.sh "$@"
    exit;;
  issue)
    shift
    issue.sh "$@"
    exit;;
  issues)
    shift
    issues.sh "$@"
    exit;;
  pullrequest)
    shift
    pullrequest.sh "$@"
    exit;;
  pr)
    shift
    pullrequest.sh "$@"
    exit;;
  pullrequests)
    shift
    pullrequests.sh "$@"
    exit;;
  prs)
    shift
    pullrequests.sh "$@"
    exit;;
  authors)
    shift
    authors.sh "$@"
    exit;;
  help)
    usage
    exit;;
  -h)
    usage
    exit;;
  -help)
    usage
    exit;;
  *)
    echo "Error: Invalid command - \""$1"\""
    exit ;;
esac
