#!/bin/bash

usage()
{
echo "
Usage: git nostr [command] [--help]

Commands:
  publish       upload commits to nostr as patches
  deleteall     send delete request for all messages for key pair
  list          list git repo manifest ids
  clone         git init, set nostr config, fetch patches for author and apply to local repo
  create        set git config.publickey to public key and upload all config patches to nostr
  pull          (not implemented) fetch patches for an author or manifestid and apply

  create-id     (not implemented) Create a git repo on nostr
  log           (not implemented) List history of updates to a repo
  fork          (not implemented) Fork a git repo on nostr
  forks         (not implemented) List forks of a repo
  issues        (not implemented) List issues for a repo
  prs           (not implemented) List pull requests for a repo
  authors       (not implemented) List contributors to a repo
  name          (not implemented) Name a repo
  named         (not implemented) Search for repos by name
  pull-request  (not implemented) Create a pull-request
  web           (not implemented) Serve a web server for repos
  help          (not implemented) Get help about a command
  reconstruct   (not implemented) Reconstruct blobs for a git-update nostr message
  find-object   (not implemented) Find a git object in a repo
 "
exit 1
}

if [ $# -lt 1 ]
then
  usage
fi

case $1 in
  publish) # display Help
    shift
    # echo `publish.sh "$@" |tee >(head -n1) >(wc -l) >/dev/null`" nostr events created"
    publish.sh "$@"
    exit;;
  deleteall)
    shift
    deleteall.sh "$@"
    exit;;
  list)
    shift
    list.sh "$@"
    exit;;
  clone)
    shift
    clone.sh "$@"
    exit;;
  create) # run git init, set nostr.privatekey, set nostr.relay
    shift
    create.sh "$@"
    exit;;
  -h)
    usage
    exit;;
  -help)
    usage
    exit;;
  *)
    echo "Error: Invalid command - \""$1"\""
    exit ;;
esac
